// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBdL0bt9zdH5wd4MNHcfe66onewlamOy4Y',
    appId: '1:289573207419:web:cdec8e76cb53ec8db7d1de',
    messagingSenderId: '289573207419',
    projectId: 'flash-chat-e93b3',
    authDomain: 'flash-chat-e93b3.firebaseapp.com',
    storageBucket: 'flash-chat-e93b3.firebasestorage.app',
    measurementId: 'G-QYX9S6NF7Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAT4Wgedl_aWC7LqjJF7twKtpCmF5TH8Kg',
    appId: '1:289573207419:android:93cd3ebbf9980875b7d1de',
    messagingSenderId: '289573207419',
    projectId: 'flash-chat-e93b3',
    storageBucket: 'flash-chat-e93b3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA0Fge6Ow1V7B91slpfUvQCCOAnI-urHik',
    appId: '1:289573207419:ios:dd9e8d09de3b8fc6b7d1de',
    messagingSenderId: '289573207419',
    projectId: 'flash-chat-e93b3',
    storageBucket: 'flash-chat-e93b3.firebasestorage.app',
    iosBundleId: 'com.example.flashChatt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA0Fge6Ow1V7B91slpfUvQCCOAnI-urHik',
    appId: '1:289573207419:ios:dd9e8d09de3b8fc6b7d1de',
    messagingSenderId: '289573207419',
    projectId: 'flash-chat-e93b3',
    storageBucket: 'flash-chat-e93b3.firebasestorage.app',
    iosBundleId: 'com.example.flashChatt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBdL0bt9zdH5wd4MNHcfe66onewlamOy4Y',
    appId: '1:289573207419:web:e1574c00302c9705b7d1de',
    messagingSenderId: '289573207419',
    projectId: 'flash-chat-e93b3',
    authDomain: 'flash-chat-e93b3.firebaseapp.com',
    storageBucket: 'flash-chat-e93b3.firebasestorage.app',
    measurementId: 'G-KYNEDKQELL',
  );
}
